# https://asukiaaa.blogspot.com/2023/04/create-zip-and-show-info-on-release-body-with-using-github-actions.html
# https://unix.stackexchange.com/questions/556545/bash-globbing-that-matches-all-files-except-those-with-a-specific-extension-tha
# https://zenn.dev/chiguniiita/articles/34f73c02f3d5a2
# https://zenn.dev/nmoa/articles/github-readme-html

name: Generate Zip file

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Download submodules
      run: git submodule update --init --recursive

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      with:
        version: 10

    - name: Install dependencies
      run: pnpm i -g markdown-to-html-cli

    - name: Convert .md to .html
      run: |
        perl bin/md2html.pl *.md docs/*.md

    - name: Create calc.html
      run: |
        cd calc
        pnpm i --frozen-lockfile --strict-peer-dependencies
        pnpm run build
        cd ..
        cp calc/dist/calc.html .

    - name: Create zip file
      run: |
        mkdir study-gears
        ls -a | grep -vE '^(\.\.?|\.git(|ignore|hub)|calc|study-gears)$' | xargs -I {} mv {} study-gears
        zip -r study-gears_${{ github.ref_name }}.zip study-gears

    - name: Upload assets
      id: upload-assets
      uses: softprops/action-gh-release@v1
      with:
        files: study-gears_${{ github.ref_name }}.zip
